name: validate
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    env:
      UNITY_EDITORS: '' # set by the setup-unity action
      UNITY_HUB_PATH: '' # set by the setup-unity action
      UNITY_EDITOR_PATH: '' # set by the setup-unity action
      UNITY_PROJECT_PATH: '' # set by the setup-unity action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        unity_versions:
          - 2019.4.40f1 (ffc62b691db5)
          - 2020.3.48f1 (b805b124c6b7)
          - 2021.3.41f1 (6c5a9e20c022)
          - 2022.3.40f1 (cbdda657d2f0)
          - 6000.0.13f1 (53a692e3fca9)
        include:
          - os: ubuntu-latest
            build_targets: StandaloneLinux64
          - os: windows-latest
            build_targets: StandaloneWindows64
          - os: macos-13
            build_targets: StandaloneOSX
            modules: mac-server
          - os: macos-latest
            build_targets: StandaloneOSX
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: RageAgainstThePixel/com.utilities.buildpipeine
          path: com.utilities.buildpipline
      - uses: RageAgainstThePixel/setup-unity@development
        with:
          unity_version: ${{ matrix.unity_versions }}
          build_targets: ${{ matrix.build_targets }}
      - uses: RageAgainstThePixel/activate-unity-license@development
        with:
          license: Personal
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}
